# Generated by Django 5.0.6 on 2024-05-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_services_bg_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/logos/')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Client Logos',
            },
        ),
    ]
