# Generated by Django 5.0.6 on 2024-05-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_logos'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Key Products',
            },
        ),
    ]
