# Generated by Django 5.0.6 on 2024-05-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_keyproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsTopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/logos/')),
            ],
            options={
                'verbose_name_plural': 'Products Top Image',
            },
        ),
    ]
